/**
 * @file test_bignum_xor_extra.c
 * @brief Extended randomized and memory-contract tests for bignum_xor.
 *
 * @details This file supplements deterministic tests with a reproducible
 * xorshift-generated fuzz campaign, a deliberately misaligned partial-overlap
 * case, and canary/source-preservation checks. The fuzz oracle is an
 * independent word-by-word inclusive-XOR model followed by high-zero
 * normalization; it never calls bignum_xor. Every assertion failure terminates
 * the process non-zero, so a passing process is evidence that all 10,000 cases
 * and all memory-contract checks passed.
 *
 * @par Seed and domain The campaign starts from fixed seed
 * `0x9E3779B97F4A7C15`; each length is uniformly generated in
 * `[0, BIGNUM_CAPACITY]`, and active words are generated by the same local
 * xorshift sequence. The exact case count is 10,000.
 * @par Ownership All objects are stack-owned by each test invocation. The API
 * must not retain pointers or modify source objects unless they are exact aliases.
 * @par Thread safety This file is single-threaded; concurrent independent
 * object calls are covered by test_bignum_xor_mt.c.
 */
/* ------------------------------------------------------------------ */
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "bignum_xor.h"

/**
 * @brief Advances the deterministic local xorshift generator.
 * @param[in,out] state Non-NULL generator state owned by the test.
 * @return The next deterministic 64-bit sample.
 * @details The generator is a reproducibility mechanism, not a security RNG.
 * Its state is private to one test process and never enters the library API.
 */
static uint64_t next_value(uint64_t *state)
{
    *state ^= *state << 7;
    *state ^= *state >> 9;
    *state ^= *state << 8;
    return *state;
}

/**
 * @brief Computes an independent normalized inclusive-XOR oracle.
 * @param[out] out Fully overwritten expected result; non-NULL.
 * @param[in] a First normalized operand; non-NULL.
 * @param[in] b Second normalized operand; non-NULL.
 * @details The model zeroes the complete output, XORs zero-extended words up to
 * the larger input length, and removes high zero words. It does not invoke or
 * share implementation helpers with bignum_xor.
 * @post `out` contains the mathematical XOR and a normalized `len`.
 */
static void model_xor(bignum_t *out, const bignum_t *a, const bignum_t *b)
{
    memset(out, 0, sizeof(*out));
    out->len = a->len > b->len ? a->len : b->len;
    for (size_t i = 0U; i < out->len; ++i) {
        uint64_t aw = i < a->len ? a->words[i] : UINT64_C(0);
        uint64_t bw = i < b->len ? b->words[i] : UINT64_C(0);
        out->words[i] = aw ^ bw;
    }
    while (out->len > 0U && out->words[out->len - 1U] == 0U) --out->len;
}

/**
 * @brief Runs 10,000 deterministic fuzz cases against the independent model.
 * @details Each generated operand length is in the inclusive legal domain
 * `[0, BIGNUM_CAPACITY]`; active words are filled from the fixed xorshift
 * sequence. The required status is `BIGNUM_XOR_SUCCESS`, and the complete
 * object byte comparison against model_xor is the oracle. Any mismatch or
 * unexpected status aborts through assert and returns a failing process code.
 */
static void test_fuzz_against_xor_model(void)
{
    uint64_t seed = UINT64_C(0x9E3779B97F4A7C15);
    for (size_t iteration = 0; iteration < 10000U; ++iteration) {
        bignum_t a;
        bignum_t b;
        bignum_t actual;
        bignum_t expected;
        a.len = (size_t)(next_value(&seed) % (BIGNUM_CAPACITY + 1U));
        b.len = (size_t)(next_value(&seed) % (BIGNUM_CAPACITY + 1U));
        memset(a.words, 0, sizeof(a.words));
        memset(b.words, 0, sizeof(b.words));
        for (size_t i = 0; i < a.len; ++i) a.words[i] = next_value(&seed);
        for (size_t i = 0; i < b.len; ++i) b.words[i] = next_value(&seed);
        model_xor(&expected, &a, &b);
        assert(bignum_xor(&actual, &a, &b) == BIGNUM_XOR_SUCCESS);
        assert(memcmp(&actual, &expected, sizeof(actual)) == 0);
    }
    puts("test_fuzz_against_xor_model: PASSED");
}

/**
 * @brief Verifies that deliberately partial object overlap is rejected.
 * @details A result pointer is formed one byte into a complete bignum_t object,
 * making its complete range overlap but not exactly equal to the source range.
 * The required status is `BIGNUM_XOR_ERROR_BUFFER_OVERLAP`; the original object
 * and both one-byte canaries must remain unchanged. This negative test proves
 * rejection occurs before destination mutation.
 */
static void test_partial_overlap_is_rejected(void)
{
    struct {
        unsigned char left;
        bignum_t objects[3];
        unsigned char right;
    } storage;
    memset(&storage, 0, sizeof(storage));
    storage.objects[0].len = 1U;
    storage.objects[0].words[0] = UINT64_MAX;
    storage.objects[1].len = 1U;
    storage.objects[1].words[0] = 0xFFU;
    bignum_t before = storage.objects[0];
    bignum_t *partial = (bignum_t *)((unsigned char *)&storage.objects[0] + 1U);
    assert(bignum_xor(partial, &storage.objects[0], &storage.objects[1]) ==
           BIGNUM_XOR_ERROR_BUFFER_OVERLAP);
    assert(memcmp(&storage.objects[0], &before, sizeof(before)) == 0);
    assert(storage.left == 0U && storage.right == 0U);
    puts("test_partial_overlap_is_rejected: PASSED");
}

/**
 * @brief Verifies source preservation and destination canaries on success.
 * @details The result is boxed between fixed 64-bit canaries while two separate
 * source operands are snapshotted byte-for-byte. A successful XOR must change
 * only the result object, preserve both source snapshots, and leave both
 * canaries equal to their fixed values. Any overwrite or source mutation is an
 * assertion failure and therefore a non-zero test result.
 */
static void test_canaries_and_source_preservation(void)
{
    struct {
        uint64_t left;
        bignum_t result;
        uint64_t right;
    } boxed;
    bignum_t a = { { UINT64_MAX, 0x1234U }, 2U };
    bignum_t b = { { 0x55U, UINT64_MAX }, 2U };
    bignum_t a_before = a;
    bignum_t b_before = b;
    boxed.left = UINT64_C(0x1111111111111111);
    boxed.right = UINT64_C(0x2222222222222222);
    assert(bignum_xor(&boxed.result, &a, &b) == BIGNUM_XOR_SUCCESS);
    assert(boxed.left == UINT64_C(0x1111111111111111));
    assert(boxed.right == UINT64_C(0x2222222222222222));
    assert(memcmp(&a, &a_before, sizeof(a)) == 0);
    assert(memcmp(&b, &b_before, sizeof(b)) == 0);
    puts("test_canaries_and_source_preservation: PASSED");
}

/**
 * @brief Runs the extended fuzz and memory-contract test group.
 * @return EXIT_SUCCESS after all assertions pass; assertion failure terminates
 * with a non-zero process status.
 * @details The completion marker is printed only after the independent oracle,
 * overlap rejection, canary, and source-preservation tests have succeeded.
 */
int main(void)
{
    puts("--- Starting extended bignum_xor tests ---");
    test_fuzz_against_xor_model();
    test_partial_overlap_is_rejected();
    test_canaries_and_source_preservation();
    puts("--- All extended bignum_xor tests passed ---");
    return 0;
}
